apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Freddyp91/managed-argocd-lab2'
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true